-- =============================================================================
-- UNCIP V2 — Schema Migration
-- Authority: docs/context/uncip/UNCIP_SCHEMA_DECISIONS.md (all decisions DECIDED)
-- Do not edit this file. Create a new numbered migration for any changes.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 7A — Reference tables (no FK dependencies)
-- ---------------------------------------------------------------------------

CREATE TABLE uncip_saps_stations (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT        NOT NULL,
  province      TEXT        NOT NULL
                            CHECK (province IN (
                              'eastern_cape','free_state','gauteng','kwazulu_natal',
                              'limpopo','mpumalanga','north_west','northern_cape','western_cape'
                            )),
  district      TEXT,
  contact_phone TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Decision: Option A — station_id on schools (sufficient for pilot scope)
CREATE TABLE uncip_schools (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT        NOT NULL,
  emis          TEXT,       -- EMIS number — nullable until safeguarding review
  province      TEXT        NOT NULL
                            CHECK (province IN (
                              'eastern_cape','free_state','gauteng','kwazulu_natal',
                              'limpopo','mpumalanga','north_west','northern_cape','western_cape'
                            )),
  address       TEXT        NOT NULL,
  contact_phone TEXT,
  contact_email TEXT,
  station_id    UUID        REFERENCES uncip_saps_stations(id),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_uncip_schools_station_id ON uncip_schools(station_id);

-- ---------------------------------------------------------------------------
-- 7A — User profiles (extends auth.users)
-- ---------------------------------------------------------------------------

CREATE TABLE uncip_user_profiles (
  id         UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email      TEXT        NOT NULL,
  name       TEXT,
  role       TEXT        NOT NULL
                         CHECK (role IN ('admin','parent','school','authority','community')),
  -- Decision 2: parent role has NULL station_id (guardian-link only scope)
  station_id UUID        REFERENCES uncip_saps_stations(id),
  school_id  UUID        REFERENCES uncip_schools(id),
  is_active  BOOLEAN     NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_uncip_user_profiles_role       ON uncip_user_profiles(role);
CREATE INDEX idx_uncip_user_profiles_station_id ON uncip_user_profiles(station_id);
CREATE INDEX idx_uncip_user_profiles_school_id  ON uncip_user_profiles(school_id);

-- ---------------------------------------------------------------------------
-- 7A — Children (central entity)
-- ---------------------------------------------------------------------------

CREATE TABLE uncip_children (
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  first_name            TEXT        NOT NULL,
  last_name             TEXT        NOT NULL,
  date_of_birth         DATE        NOT NULL,
  gender                TEXT        NOT NULL
                                    CHECK (gender IN ('male','female','other')),
  photo_url             TEXT,
  -- Decision 1: nullable — required before missing alert, not at registration
  identification_number TEXT,
  school_id             UUID        REFERENCES uncip_schools(id),
  -- ChildAddress columns (single address, no separate table)
  address_street        TEXT,
  address_city          TEXT,
  address_province      TEXT
                        CHECK (address_province IN (
                          'eastern_cape','free_state','gauteng','kwazulu_natal',
                          'limpopo','mpumalanga','north_west','northern_cape','western_cape'
                        )),
  address_postal_code   TEXT,
  created_by            UUID        NOT NULL REFERENCES auth.users(id),
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_uncip_children_school_id  ON uncip_children(school_id);
CREATE INDEX idx_uncip_children_created_by ON uncip_children(created_by);

CREATE TRIGGER trg_uncip_children_updated_at
  BEFORE UPDATE ON uncip_children
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 7A — Child medical (POPIA special category — separate table)
-- ---------------------------------------------------------------------------

CREATE TABLE uncip_child_medical (
  id                             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id                       UUID        NOT NULL UNIQUE REFERENCES uncip_children(id) ON DELETE CASCADE,
  blood_type                     TEXT,
  allergies                      TEXT[]      NOT NULL DEFAULT '{}',
  conditions                     TEXT[]      NOT NULL DEFAULT '{}',
  medications                    TEXT[]      NOT NULL DEFAULT '{}',
  emergency_contact_name         TEXT,
  emergency_contact_relationship TEXT,
  emergency_contact_phone        TEXT,
  created_at                     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_uncip_child_medical_updated_at
  BEFORE UPDATE ON uncip_child_medical
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 7A — Guardian links
-- ---------------------------------------------------------------------------

CREATE TABLE uncip_guardian_links (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id     UUID        NOT NULL REFERENCES uncip_children(id) ON DELETE CASCADE,
  user_id      UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  relationship TEXT        NOT NULL
                           CHECK (relationship IN ('parent','grandparent','foster_carer','other')),
  is_primary   BOOLEAN     NOT NULL DEFAULT false,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (child_id, user_id)
);

CREATE INDEX idx_uncip_guardian_links_user_id  ON uncip_guardian_links(user_id);
CREATE INDEX idx_uncip_guardian_links_child_id ON uncip_guardian_links(child_id);

-- ---------------------------------------------------------------------------
-- 7A — Alerts
-- ---------------------------------------------------------------------------

CREATE TABLE uncip_alerts (
  id                 UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id           UUID        NOT NULL REFERENCES uncip_children(id),
  alert_type         TEXT        NOT NULL
                                 CHECK (alert_type IN ('missing','medical','danger','other')),
  status             TEXT        NOT NULL DEFAULT 'active'
                                 CHECK (status IN ('active','resolved','cancelled','false_alarm')),
  description        TEXT        NOT NULL,
  last_seen_at       TIMESTAMPTZ NOT NULL,
  last_seen_location TEXT        NOT NULL,
  last_seen_wearing  TEXT,
  contact_phone      TEXT        NOT NULL,
  created_by         UUID        NOT NULL REFERENCES auth.users(id),
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at        TIMESTAMPTZ,
  resolved_by        UUID        REFERENCES auth.users(id)
);

CREATE INDEX idx_uncip_alerts_child_id   ON uncip_alerts(child_id);
CREATE INDEX idx_uncip_alerts_status     ON uncip_alerts(status);
CREATE INDEX idx_uncip_alerts_created_by ON uncip_alerts(created_by);

CREATE TRIGGER trg_uncip_alerts_updated_at
  BEFORE UPDATE ON uncip_alerts
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 7A — Alert timeline (immutable append-only)
-- ---------------------------------------------------------------------------

CREATE TABLE uncip_alert_timeline (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  alert_id   UUID        NOT NULL REFERENCES uncip_alerts(id) ON DELETE CASCADE,
  actor_id   UUID        NOT NULL REFERENCES auth.users(id),
  -- Denormalised: role at time of action — user role may change later
  actor_role TEXT        NOT NULL
                         CHECK (actor_role IN ('admin','parent','school','authority','community')),
  action     TEXT        NOT NULL
                         CHECK (action IN (
                           'alert_raised',
                           'school_confirmed_last_seen',
                           'authority_assigned_case',
                           'community_sighting_reported',
                           'status_changed',
                           'note_added'
                         )),
  note       TEXT,
  timestamp  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_uncip_alert_timeline_alert_id ON uncip_alert_timeline(alert_id);
CREATE INDEX idx_uncip_alert_timeline_actor_id ON uncip_alert_timeline(actor_id);

-- No UPDATE or DELETE trigger — immutability enforced by RLS (INSERT only for authenticated)

-- ---------------------------------------------------------------------------
-- 7C/7D — Profile session function (security-definer, cached per transaction)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION uncip_current_profile()
RETURNS uncip_user_profiles
LANGUAGE sql STABLE SECURITY DEFINER
AS $$
  SELECT * FROM uncip_user_profiles WHERE id = auth.uid()
$$;

-- ---------------------------------------------------------------------------
-- 7E — Enable RLS on all UNCIP tables
-- ---------------------------------------------------------------------------

ALTER TABLE uncip_saps_stations   ENABLE ROW LEVEL SECURITY;
ALTER TABLE uncip_schools         ENABLE ROW LEVEL SECURITY;
ALTER TABLE uncip_user_profiles   ENABLE ROW LEVEL SECURITY;
ALTER TABLE uncip_children        ENABLE ROW LEVEL SECURITY;
ALTER TABLE uncip_child_medical   ENABLE ROW LEVEL SECURITY;
ALTER TABLE uncip_guardian_links  ENABLE ROW LEVEL SECURITY;
ALTER TABLE uncip_alerts          ENABLE ROW LEVEL SECURITY;
ALTER TABLE uncip_alert_timeline  ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- 7E — uncip_saps_stations policies
-- All authenticated users read. Admin writes.
-- ---------------------------------------------------------------------------

CREATE POLICY "uncip_stations_read" ON uncip_saps_stations
  FOR SELECT TO authenticated
  USING (true);

CREATE POLICY "uncip_stations_admin_write" ON uncip_saps_stations
  FOR ALL TO authenticated
  USING ((uncip_current_profile()).role = 'admin')
  WITH CHECK ((uncip_current_profile()).role = 'admin');

-- ---------------------------------------------------------------------------
-- 7E — uncip_schools policies
-- Admin: all. School: own row. Authority: station area. Others: read only.
-- ---------------------------------------------------------------------------

CREATE POLICY "uncip_schools_read" ON uncip_schools
  FOR SELECT TO authenticated
  USING (
    (uncip_current_profile()).role IN ('admin','parent','authority','community')
    OR (
      (uncip_current_profile()).role = 'school'
      AND id = (uncip_current_profile()).school_id
    )
    OR (
      (uncip_current_profile()).role = 'authority'
      AND station_id = (uncip_current_profile()).station_id
    )
  );

CREATE POLICY "uncip_schools_admin_write" ON uncip_schools
  FOR ALL TO authenticated
  USING ((uncip_current_profile()).role = 'admin')
  WITH CHECK ((uncip_current_profile()).role = 'admin');

-- ---------------------------------------------------------------------------
-- 7E — uncip_user_profiles policies
-- Own row always. Admin: all rows + write.
-- ---------------------------------------------------------------------------

CREATE POLICY "uncip_profiles_own" ON uncip_user_profiles
  FOR SELECT TO authenticated
  USING (id = auth.uid());

CREATE POLICY "uncip_profiles_admin_all" ON uncip_user_profiles
  FOR ALL TO authenticated
  USING ((uncip_current_profile()).role = 'admin')
  WITH CHECK ((uncip_current_profile()).role = 'admin');

CREATE POLICY "uncip_profiles_insert_own" ON uncip_user_profiles
  FOR INSERT TO authenticated
  WITH CHECK (id = auth.uid());

-- ---------------------------------------------------------------------------
-- 7E — uncip_children policies
-- ---------------------------------------------------------------------------

-- Admin: all
CREATE POLICY "uncip_children_admin" ON uncip_children
  FOR ALL TO authenticated
  USING ((uncip_current_profile()).role = 'admin')
  WITH CHECK ((uncip_current_profile()).role = 'admin');

-- Parent: children they are guardian of
CREATE POLICY "uncip_children_parent_read" ON uncip_children
  FOR SELECT TO authenticated
  USING (
    (uncip_current_profile()).role = 'parent'
    AND EXISTS (
      SELECT 1 FROM uncip_guardian_links
      WHERE child_id = uncip_children.id
        AND user_id = auth.uid()
    )
  );

CREATE POLICY "uncip_children_parent_insert" ON uncip_children
  FOR INSERT TO authenticated
  WITH CHECK (
    (uncip_current_profile()).role = 'parent'
    AND created_by = auth.uid()
  );

CREATE POLICY "uncip_children_parent_update" ON uncip_children
  FOR UPDATE TO authenticated
  USING (
    (uncip_current_profile()).role = 'parent'
    AND EXISTS (
      SELECT 1 FROM uncip_guardian_links
      WHERE child_id = uncip_children.id
        AND user_id = auth.uid()
    )
  );

-- School: children enrolled at their school
CREATE POLICY "uncip_children_school_read" ON uncip_children
  FOR SELECT TO authenticated
  USING (
    (uncip_current_profile()).role = 'school'
    AND school_id = (uncip_current_profile()).school_id
  );

-- Authority: children whose school is in their station area
CREATE POLICY "uncip_children_authority_read" ON uncip_children
  FOR SELECT TO authenticated
  USING (
    (uncip_current_profile()).role = 'authority'
    AND (
      school_id IN (
        SELECT id FROM uncip_schools
        WHERE station_id = (uncip_current_profile()).station_id
      )
      OR EXISTS (
        SELECT 1 FROM uncip_alerts a
        JOIN uncip_children c2 ON c2.id = a.child_id
        JOIN uncip_schools s ON s.id = c2.school_id
        WHERE a.child_id = uncip_children.id
          AND s.station_id = (uncip_current_profile()).station_id
      )
    )
  );

-- Community: NO access to child identity records (safeguarding boundary)

-- ---------------------------------------------------------------------------
-- 7E — uncip_child_medical policies
-- POPIA special category — independent access control
-- ---------------------------------------------------------------------------

-- Admin: all
CREATE POLICY "uncip_child_medical_admin" ON uncip_child_medical
  FOR ALL TO authenticated
  USING ((uncip_current_profile()).role = 'admin')
  WITH CHECK ((uncip_current_profile()).role = 'admin');

-- Parent: own children
CREATE POLICY "uncip_child_medical_parent" ON uncip_child_medical
  FOR ALL TO authenticated
  USING (
    (uncip_current_profile()).role = 'parent'
    AND EXISTS (
      SELECT 1 FROM uncip_guardian_links
      WHERE child_id = uncip_child_medical.child_id
        AND user_id = auth.uid()
    )
  )
  WITH CHECK (
    (uncip_current_profile()).role = 'parent'
    AND EXISTS (
      SELECT 1 FROM uncip_guardian_links
      WHERE child_id = uncip_child_medical.child_id
        AND user_id = auth.uid()
    )
  );

-- School: enrolled children
CREATE POLICY "uncip_child_medical_school_read" ON uncip_child_medical
  FOR SELECT TO authenticated
  USING (
    (uncip_current_profile()).role = 'school'
    AND EXISTS (
      SELECT 1 FROM uncip_children
      WHERE id = uncip_child_medical.child_id
        AND school_id = (uncip_current_profile()).school_id
    )
  );

-- Authority: station area (emergency access)
CREATE POLICY "uncip_child_medical_authority_read" ON uncip_child_medical
  FOR SELECT TO authenticated
  USING (
    (uncip_current_profile()).role = 'authority'
    AND EXISTS (
      SELECT 1 FROM uncip_children c
      JOIN uncip_schools s ON s.id = c.school_id
      WHERE c.id = uncip_child_medical.child_id
        AND s.station_id = (uncip_current_profile()).station_id
    )
  );

-- Community: NO access

-- ---------------------------------------------------------------------------
-- 7E — uncip_guardian_links policies
-- ---------------------------------------------------------------------------

-- Admin: all
CREATE POLICY "uncip_guardian_links_admin" ON uncip_guardian_links
  FOR ALL TO authenticated
  USING ((uncip_current_profile()).role = 'admin')
  WITH CHECK ((uncip_current_profile()).role = 'admin');

-- Parent: own links
CREATE POLICY "uncip_guardian_links_parent" ON uncip_guardian_links
  FOR ALL TO authenticated
  USING (
    (uncip_current_profile()).role = 'parent'
    AND user_id = auth.uid()
  )
  WITH CHECK (
    (uncip_current_profile()).role = 'parent'
    AND user_id = auth.uid()
  );

-- School: read links for enrolled children
CREATE POLICY "uncip_guardian_links_school_read" ON uncip_guardian_links
  FOR SELECT TO authenticated
  USING (
    (uncip_current_profile()).role = 'school'
    AND EXISTS (
      SELECT 1 FROM uncip_children
      WHERE id = uncip_guardian_links.child_id
        AND school_id = (uncip_current_profile()).school_id
    )
  );

-- Authority: read links for station area children
CREATE POLICY "uncip_guardian_links_authority_read" ON uncip_guardian_links
  FOR SELECT TO authenticated
  USING (
    (uncip_current_profile()).role = 'authority'
    AND EXISTS (
      SELECT 1 FROM uncip_children c
      JOIN uncip_schools s ON s.id = c.school_id
      WHERE c.id = uncip_guardian_links.child_id
        AND s.station_id = (uncip_current_profile()).station_id
    )
  );

-- Community: NO access

-- ---------------------------------------------------------------------------
-- 7E — uncip_alerts policies
-- ---------------------------------------------------------------------------

-- Admin: all
CREATE POLICY "uncip_alerts_admin" ON uncip_alerts
  FOR ALL TO authenticated
  USING ((uncip_current_profile()).role = 'admin')
  WITH CHECK ((uncip_current_profile()).role = 'admin');

-- Parent: alerts for their children
CREATE POLICY "uncip_alerts_parent_read" ON uncip_alerts
  FOR SELECT TO authenticated
  USING (
    (uncip_current_profile()).role = 'parent'
    AND EXISTS (
      SELECT 1 FROM uncip_guardian_links
      WHERE child_id = uncip_alerts.child_id
        AND user_id = auth.uid()
    )
  );

-- Decision 3a: parent can raise alert; Decision 1: missing alert requires identification_number
-- Enforcement of identification_number check is in the Edge Function, not RLS
CREATE POLICY "uncip_alerts_parent_insert" ON uncip_alerts
  FOR INSERT TO authenticated
  WITH CHECK (
    (uncip_current_profile()).role = 'parent'
    AND created_by = auth.uid()
    AND EXISTS (
      SELECT 1 FROM uncip_guardian_links
      WHERE child_id = uncip_alerts.child_id
        AND user_id = auth.uid()
    )
  );

CREATE POLICY "uncip_alerts_parent_update" ON uncip_alerts
  FOR UPDATE TO authenticated
  USING (
    (uncip_current_profile()).role = 'parent'
    AND created_by = auth.uid()
  );

-- School: alerts for enrolled children
-- Decision 3a: school can raise medical alerts only — enforced in Edge Function
CREATE POLICY "uncip_alerts_school_read" ON uncip_alerts
  FOR SELECT TO authenticated
  USING (
    (uncip_current_profile()).role = 'school'
    AND EXISTS (
      SELECT 1 FROM uncip_children
      WHERE id = uncip_alerts.child_id
        AND school_id = (uncip_current_profile()).school_id
    )
  );

CREATE POLICY "uncip_alerts_school_insert" ON uncip_alerts
  FOR INSERT TO authenticated
  WITH CHECK (
    (uncip_current_profile()).role = 'school'
    AND created_by = auth.uid()
    AND EXISTS (
      SELECT 1 FROM uncip_children
      WHERE id = uncip_alerts.child_id
        AND school_id = (uncip_current_profile()).school_id
    )
  );

-- Authority: alerts in their station area
CREATE POLICY "uncip_alerts_authority_read" ON uncip_alerts
  FOR SELECT TO authenticated
  USING (
    (uncip_current_profile()).role = 'authority'
    AND EXISTS (
      SELECT 1 FROM uncip_children c
      JOIN uncip_schools s ON s.id = c.school_id
      WHERE c.id = uncip_alerts.child_id
        AND s.station_id = (uncip_current_profile()).station_id
    )
  );

CREATE POLICY "uncip_alerts_authority_update" ON uncip_alerts
  FOR UPDATE TO authenticated
  USING (
    (uncip_current_profile()).role = 'authority'
    AND EXISTS (
      SELECT 1 FROM uncip_children c
      JOIN uncip_schools s ON s.id = c.school_id
      WHERE c.id = uncip_alerts.child_id
        AND s.station_id = (uncip_current_profile()).station_id
    )
  );

-- Community: read active alerts in their station area only
-- Safeguarding: community sees alert metadata, NOT child identity (enforced by separate table policies)
CREATE POLICY "uncip_alerts_community_read" ON uncip_alerts
  FOR SELECT TO authenticated
  USING (
    (uncip_current_profile()).role = 'community'
    AND status = 'active'
    AND EXISTS (
      SELECT 1 FROM uncip_children c
      JOIN uncip_schools s ON s.id = c.school_id
      WHERE c.id = uncip_alerts.child_id
        AND s.station_id = (uncip_current_profile()).station_id
    )
  );

-- ---------------------------------------------------------------------------
-- 7E — uncip_alert_timeline policies
-- Immutable: authenticated users INSERT only (no UPDATE, no DELETE via RLS)
-- Decision 3: approved permission table enforced here + Edge Function
-- ---------------------------------------------------------------------------

-- Admin: all
CREATE POLICY "uncip_timeline_admin" ON uncip_alert_timeline
  FOR ALL TO authenticated
  USING ((uncip_current_profile()).role = 'admin')
  WITH CHECK ((uncip_current_profile()).role = 'admin');

-- Parent: read own alert timelines; insert alert_raised / status_changed / note_added
CREATE POLICY "uncip_timeline_parent_read" ON uncip_alert_timeline
  FOR SELECT TO authenticated
  USING (
    (uncip_current_profile()).role = 'parent'
    AND EXISTS (
      SELECT 1 FROM uncip_alerts a
      JOIN uncip_guardian_links gl ON gl.child_id = a.child_id
      WHERE a.id = uncip_alert_timeline.alert_id
        AND gl.user_id = auth.uid()
    )
  );

CREATE POLICY "uncip_timeline_parent_insert" ON uncip_alert_timeline
  FOR INSERT TO authenticated
  WITH CHECK (
    (uncip_current_profile()).role = 'parent'
    AND actor_id = auth.uid()
    AND action IN ('alert_raised','status_changed','note_added')
    AND EXISTS (
      SELECT 1 FROM uncip_alerts a
      JOIN uncip_guardian_links gl ON gl.child_id = a.child_id
      WHERE a.id = uncip_alert_timeline.alert_id
        AND gl.user_id = auth.uid()
    )
  );

-- School: read enrolled children timelines; insert school_confirmed_last_seen / note_added
-- Decision 3a: alert_raised for medical only — enforced in Edge Function
CREATE POLICY "uncip_timeline_school_read" ON uncip_alert_timeline
  FOR SELECT TO authenticated
  USING (
    (uncip_current_profile()).role = 'school'
    AND EXISTS (
      SELECT 1 FROM uncip_alerts a
      JOIN uncip_children c ON c.id = a.child_id
      WHERE a.id = uncip_alert_timeline.alert_id
        AND c.school_id = (uncip_current_profile()).school_id
    )
  );

CREATE POLICY "uncip_timeline_school_insert" ON uncip_alert_timeline
  FOR INSERT TO authenticated
  WITH CHECK (
    (uncip_current_profile()).role = 'school'
    AND actor_id = auth.uid()
    AND action IN ('alert_raised','school_confirmed_last_seen','note_added')
    AND EXISTS (
      SELECT 1 FROM uncip_alerts a
      JOIN uncip_children c ON c.id = a.child_id
      WHERE a.id = uncip_alert_timeline.alert_id
        AND c.school_id = (uncip_current_profile()).school_id
    )
  );

-- Authority: read station area timelines; insert authority_assigned_case / status_changed / note_added
CREATE POLICY "uncip_timeline_authority_read" ON uncip_alert_timeline
  FOR SELECT TO authenticated
  USING (
    (uncip_current_profile()).role = 'authority'
    AND EXISTS (
      SELECT 1 FROM uncip_alerts a
      JOIN uncip_children c ON c.id = a.child_id
      JOIN uncip_schools s ON s.id = c.school_id
      WHERE a.id = uncip_alert_timeline.alert_id
        AND s.station_id = (uncip_current_profile()).station_id
    )
  );

CREATE POLICY "uncip_timeline_authority_insert" ON uncip_alert_timeline
  FOR INSERT TO authenticated
  WITH CHECK (
    (uncip_current_profile()).role = 'authority'
    AND actor_id = auth.uid()
    AND action IN ('authority_assigned_case','status_changed','note_added')
    AND EXISTS (
      SELECT 1 FROM uncip_alerts a
      JOIN uncip_children c ON c.id = a.child_id
      JOIN uncip_schools s ON s.id = c.school_id
      WHERE a.id = uncip_alert_timeline.alert_id
        AND s.station_id = (uncip_current_profile()).station_id
    )
  );

-- Community: read station area timelines; insert community_sighting_reported / note_added
CREATE POLICY "uncip_timeline_community_read" ON uncip_alert_timeline
  FOR SELECT TO authenticated
  USING (
    (uncip_current_profile()).role = 'community'
    AND EXISTS (
      SELECT 1 FROM uncip_alerts a
      JOIN uncip_children c ON c.id = a.child_id
      JOIN uncip_schools s ON s.id = c.school_id
      WHERE a.id = uncip_alert_timeline.alert_id
        AND s.station_id = (uncip_current_profile()).station_id
    )
  );

CREATE POLICY "uncip_timeline_community_insert" ON uncip_alert_timeline
  FOR INSERT TO authenticated
  WITH CHECK (
    (uncip_current_profile()).role = 'community'
    AND actor_id = auth.uid()
    AND action IN ('community_sighting_reported','note_added')
    AND EXISTS (
      SELECT 1 FROM uncip_alerts a
      JOIN uncip_children c ON c.id = a.child_id
      JOIN uncip_schools s ON s.id = c.school_id
      WHERE a.id = uncip_alert_timeline.alert_id
        AND s.station_id = (uncip_current_profile()).station_id
    )
  );
