-- =============================================================================
-- Moments v2 — Initial Schema
-- Source of truth: docs/DATABASE_SCHEMA.md
-- Do not edit this file. Create a new numbered migration for any changes.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------------
-- Utility: set_updated_at trigger function
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- 1. sponsors
-- (no FK dependencies — must exist before moments and campaigns)
-- ---------------------------------------------------------------------------

CREATE TABLE sponsors (
  id             UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  name           TEXT          NOT NULL UNIQUE,
  display_name   TEXT          NOT NULL,
  contact_email  TEXT,
  logo_url       TEXT,
  website_url    TEXT,
  tier           TEXT          NOT NULL DEFAULT 'bronze'
                               CHECK (tier IN ('bronze','silver','gold','platinum')),
  monthly_budget DECIMAL(10,2) NOT NULL DEFAULT 0,
  active         BOOLEAN       NOT NULL DEFAULT true,
  created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_sponsors_updated_at
  BEFORE UPDATE ON sponsors
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 2. moments
-- ---------------------------------------------------------------------------

CREATE TABLE moments (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  title               TEXT        NOT NULL CHECK (char_length(title) BETWEEN 3 AND 200),
  content             TEXT        NOT NULL CHECK (char_length(content) BETWEEN 10 AND 2000),
  raw_content         TEXT,
  region              TEXT        NOT NULL
                                  CHECK (region IN ('KZN','WC','GP','EC','FS','LP','MP','NC','NW','National')),
  category            TEXT        NOT NULL
                                  CHECK (category IN ('Education','Safety','Culture','Opportunity','Events','Health','Technology','Community')),
  language            TEXT        NOT NULL DEFAULT 'eng'
                                  CHECK (language IN ('eng','zul','xho','afr')),
  sponsor_id          UUID        REFERENCES sponsors(id) ON DELETE SET NULL,
  is_sponsored        BOOLEAN     NOT NULL DEFAULT false,
  pwa_link            TEXT,
  media_urls          TEXT[]      NOT NULL DEFAULT '{}',
  scheduled_at        TIMESTAMPTZ,
  broadcasted_at      TIMESTAMPTZ,
  status              TEXT        NOT NULL DEFAULT 'draft'
                                  CHECK (status IN ('draft','scheduled','broadcasted','cancelled')),
  urgency_level       TEXT        NOT NULL DEFAULT 'low'
                                  CHECK (urgency_level IN ('low','medium','high','urgent')),
  content_source      TEXT        NOT NULL DEFAULT 'admin'
                                  CHECK (content_source IN ('admin','community','whatsapp','campaign')),
  created_by          TEXT,
  publish_to_whatsapp BOOLEAN     NOT NULL DEFAULT false,
  publish_to_pwa      BOOLEAN     NOT NULL DEFAULT true,
  digest_sent         TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_moments_status         ON moments(status);
CREATE INDEX idx_moments_region         ON moments(region);
CREATE INDEX idx_moments_category       ON moments(category);
CREATE INDEX idx_moments_content_source ON moments(content_source);
CREATE INDEX idx_moments_scheduled_at   ON moments(scheduled_at);
CREATE INDEX idx_moments_sponsor_id     ON moments(sponsor_id);

CREATE TRIGGER trg_moments_updated_at
  BEFORE UPDATE ON moments
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 3. campaigns
-- ---------------------------------------------------------------------------

CREATE TABLE campaigns (
  id                UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  title             TEXT          NOT NULL,
  content           TEXT          NOT NULL,
  category          TEXT          NOT NULL
                                  CHECK (category IN ('Education','Safety','Culture','Opportunity','Events','Health','Technology','Community')),
  sponsor_id        UUID          REFERENCES sponsors(id) ON DELETE SET NULL,
  budget            DECIMAL(10,2) NOT NULL DEFAULT 0,
  target_regions    TEXT[]        NOT NULL DEFAULT '{}',
  target_categories TEXT[]        NOT NULL DEFAULT '{}',
  media_urls        TEXT[]        NOT NULL DEFAULT '{}',
  scheduled_at      TIMESTAMPTZ,
  status            TEXT          NOT NULL DEFAULT 'pending_review'
                                  CHECK (status IN ('pending_review','approved','active','paused','completed','cancelled','published')),
  template_name     TEXT,
  created_by        TEXT,
  created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_campaigns_updated_at
  BEFORE UPDATE ON campaigns
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 4. moment_intents
-- ---------------------------------------------------------------------------

CREATE TABLE moment_intents (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  moment_id       UUID        NOT NULL REFERENCES moments(id) ON DELETE CASCADE,
  channel         TEXT        NOT NULL CHECK (channel IN ('pwa','whatsapp','email','sms')),
  action          TEXT        NOT NULL CHECK (action IN ('publish','update','delete')),
  status          TEXT        NOT NULL DEFAULT 'pending'
                              CHECK (status IN ('pending','processing','sent','failed','cancelled')),
  template_id     TEXT,
  payload         JSONB,
  attempts        INTEGER     NOT NULL DEFAULT 0,
  last_attempt_at TIMESTAMPTZ,
  last_error      TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (moment_id, channel)
);

CREATE TRIGGER trg_moment_intents_updated_at
  BEFORE UPDATE ON moment_intents
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 5. broadcasts
-- ---------------------------------------------------------------------------

CREATE TABLE broadcasts (
  id                      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  moment_id               UUID        NOT NULL REFERENCES moments(id) ON DELETE CASCADE,
  campaign_id             UUID        REFERENCES campaigns(id) ON DELETE SET NULL,
  recipient_count         INTEGER     NOT NULL DEFAULT 0 CHECK (recipient_count >= 0),
  success_count           INTEGER     NOT NULL DEFAULT 0 CHECK (success_count >= 0),
  failure_count           INTEGER     NOT NULL DEFAULT 0 CHECK (failure_count >= 0),
  broadcast_started_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  broadcast_completed_at  TIMESTAMPTZ,
  status                  TEXT        NOT NULL
                                      CHECK (status IN ('pending','processing','completed','failed')),
  authority_context       JSONB,
  error_details           JSONB,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 6. broadcast_batches
-- ---------------------------------------------------------------------------

CREATE TABLE broadcast_batches (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  broadcast_id UUID        NOT NULL REFERENCES broadcasts(id) ON DELETE CASCADE,
  batch_number INTEGER     NOT NULL,
  recipients   TEXT[]      NOT NULL,
  status       TEXT        NOT NULL CHECK (status IN ('pending','processing','completed','failed')),
  success_count INTEGER    NOT NULL DEFAULT 0,
  failure_count INTEGER    NOT NULL DEFAULT 0,
  started_at   TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 7. subscriptions
-- ---------------------------------------------------------------------------

CREATE TABLE subscriptions (
  id                     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  phone_number           TEXT        NOT NULL UNIQUE
                                     CHECK (phone_number ~ '^\+[1-9]\d{1,14}$'),
  opted_in               BOOLEAN     NOT NULL DEFAULT true,
  regions                TEXT[]      NOT NULL DEFAULT '{National}',
  categories             TEXT[]      NOT NULL DEFAULT '{Education,Safety,Culture,Opportunity,Events,Health,Technology,Community}',
  language_preference    TEXT        NOT NULL DEFAULT 'eng'
                                     CHECK (language_preference IN ('eng','zul','xho','afr')),
  delivery_schedule      TEXT        NOT NULL DEFAULT 'instant'
                                     CHECK (delivery_schedule IN ('instant','morning','evening','weekly')),
  paused_until           TIMESTAMPTZ,
  opted_in_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  opted_out_at           TIMESTAMPTZ,
  last_activity          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  consent_timestamp      TIMESTAMPTZ,
  consent_method         TEXT,
  double_opt_in_confirmed BOOLEAN    NOT NULL DEFAULT false,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_subscriptions_opted_in          ON subscriptions(opted_in);
CREATE INDEX idx_subscriptions_delivery_schedule ON subscriptions(delivery_schedule);
CREATE INDEX idx_subscriptions_regions           ON subscriptions USING GIN(regions);
CREATE INDEX idx_subscriptions_categories        ON subscriptions USING GIN(categories);

-- ---------------------------------------------------------------------------
-- 8. messages
-- ---------------------------------------------------------------------------

CREATE TABLE messages (
  id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  whatsapp_id       TEXT        NOT NULL UNIQUE,
  from_number       TEXT        NOT NULL,
  message_type      TEXT        NOT NULL CHECK (message_type IN ('text','image','audio','video','document')),
  content           TEXT,
  media_url         TEXT,
  media_id          TEXT,
  language_detected TEXT,
  authority_context JSONB,
  timestamp         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed         BOOLEAN     NOT NULL DEFAULT false,
  moderation_status TEXT        NOT NULL DEFAULT 'pending'
                                CHECK (moderation_status IN ('pending','approved','flagged','rejected')),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_messages_from_number       ON messages(from_number);
CREATE INDEX idx_messages_moderation_status ON messages(moderation_status);
CREATE INDEX idx_messages_processed         ON messages(processed);
CREATE INDEX idx_messages_timestamp         ON messages(timestamp);

CREATE TRIGGER trg_messages_updated_at
  BEFORE UPDATE ON messages
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 9. advisories
-- ---------------------------------------------------------------------------

CREATE TABLE advisories (
  id                   UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id           UUID          REFERENCES messages(id) ON DELETE CASCADE,
  moment_id            UUID          REFERENCES moments(id) ON DELETE CASCADE,
  advisory_type        TEXT          NOT NULL
                                     CHECK (advisory_type IN ('language','urgency','harm','spam','content_quality')),
  confidence           DECIMAL(3,2)  NOT NULL CHECK (confidence BETWEEN 0 AND 1),
  harm_signals         JSONB,
  spam_indicators      JSONB,
  urgency_level        TEXT          NOT NULL DEFAULT 'low'
                                     CHECK (urgency_level IN ('low','medium','high','urgent')),
  escalation_suggested BOOLEAN       NOT NULL DEFAULT false,
  details              JSONB,
  created_at           TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  CHECK (message_id IS NOT NULL OR moment_id IS NOT NULL)
);

-- ---------------------------------------------------------------------------
-- 10. moderation_audit
-- ---------------------------------------------------------------------------

CREATE TABLE moderation_audit (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id UUID        REFERENCES messages(id) ON DELETE CASCADE,
  moment_id  UUID        REFERENCES moments(id) ON DELETE CASCADE,
  action     TEXT        NOT NULL CHECK (action IN ('approved','flagged','rejected')),
  moderator  TEXT        NOT NULL,
  reason     TEXT,
  timestamp  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 11. comments
-- ---------------------------------------------------------------------------

CREATE TABLE comments (
  id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  moment_id         UUID        NOT NULL REFERENCES moments(id) ON DELETE CASCADE,
  from_number       TEXT        NOT NULL,
  content           TEXT        NOT NULL CHECK (char_length(content) <= 500),
  moderation_status TEXT        NOT NULL DEFAULT 'pending'
                                CHECK (moderation_status IN ('pending','approved','rejected')),
  featured          BOOLEAN     NOT NULL DEFAULT false,
  reply_count       INTEGER     NOT NULL DEFAULT 0,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_comments_updated_at
  BEFORE UPDATE ON comments
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 12. whatsapp_comments
-- ---------------------------------------------------------------------------

CREATE TABLE whatsapp_comments (
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  whatsapp_message_id   TEXT        NOT NULL UNIQUE,
  comment_id            UUID        REFERENCES comments(id) ON DELETE CASCADE,
  from_number           TEXT        NOT NULL,
  moment_id             UUID        NOT NULL REFERENCES moments(id) ON DELETE CASCADE,
  reply_to_message_id   TEXT,
  media_type            TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_whatsapp_comments_updated_at
  BEFORE UPDATE ON whatsapp_comments
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 13. authority_profiles
-- ---------------------------------------------------------------------------

CREATE TABLE authority_profiles (
  id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_identifier  TEXT         NOT NULL,
  authority_level  INTEGER      NOT NULL DEFAULT 1 CHECK (authority_level BETWEEN 1 AND 5),
  role_label       TEXT         NOT NULL,
  scope            TEXT         NOT NULL CHECK (scope IN ('community','region','province','national')),
  scope_identifier TEXT,
  approval_mode    TEXT         NOT NULL DEFAULT 'admin_review'
                                CHECK (approval_mode IN ('admin_review','ai_review','auto')),
  blast_radius     INTEGER      NOT NULL DEFAULT 100 CHECK (blast_radius BETWEEN 1 AND 10000),
  risk_threshold   DECIMAL(3,2) NOT NULL DEFAULT 0.7 CHECK (risk_threshold BETWEEN 0.1 AND 0.9),
  status           TEXT         NOT NULL DEFAULT 'active'
                                CHECK (status IN ('active','suspended','expired')),
  valid_until      TIMESTAMPTZ,
  metadata         JSONB        NOT NULL DEFAULT '{}',
  created_by       TEXT,
  updated_by       TEXT,
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_authority_profiles_updated_at
  BEFORE UPDATE ON authority_profiles
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 14. authority_audit_log
-- ---------------------------------------------------------------------------

CREATE TABLE authority_audit_log (
  id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  authority_profile_id UUID        NOT NULL REFERENCES authority_profiles(id) ON DELETE CASCADE,
  action               TEXT        NOT NULL CHECK (action IN ('created','updated','suspended','enforced')),
  actor_id             TEXT        NOT NULL,
  context              JSONB,
  timestamp            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 15. admin_roles
-- ---------------------------------------------------------------------------

CREATE TABLE admin_roles (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID        NOT NULL UNIQUE,
  role       TEXT        NOT NULL CHECK (role IN ('superadmin','content_admin','moderator','viewer')),
  granted_by TEXT,
  granted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 16. media
-- ---------------------------------------------------------------------------

CREATE TABLE media (
  id                 UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id         UUID        REFERENCES messages(id) ON DELETE CASCADE,
  moment_id          UUID        REFERENCES moments(id) ON DELETE CASCADE,
  whatsapp_media_id  TEXT,
  media_type         TEXT        NOT NULL CHECK (media_type IN ('image','audio','video','document')),
  original_url       TEXT,
  storage_path       TEXT,
  file_size          BIGINT      NOT NULL CHECK (file_size > 0),
  mime_type          TEXT,
  processed          BOOLEAN     NOT NULL DEFAULT false,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 17. moment_stats
-- ---------------------------------------------------------------------------

CREATE TABLE moment_stats (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  moment_id      UUID        NOT NULL UNIQUE REFERENCES moments(id) ON DELETE CASCADE,
  view_count     INTEGER     NOT NULL DEFAULT 0,
  comment_count  INTEGER     NOT NULL DEFAULT 0,
  share_count    INTEGER     NOT NULL DEFAULT 0,
  reaction_count INTEGER     NOT NULL DEFAULT 0,
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_moment_stats_updated_at
  BEFORE UPDATE ON moment_stats
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 18. user_profiles
-- ---------------------------------------------------------------------------

CREATE TABLE user_profiles (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  phone_number     TEXT        NOT NULL UNIQUE,
  display_name     TEXT,
  avatar_url       TEXT,
  bio              TEXT        CHECK (char_length(bio) <= 200),
  reputation_score INTEGER     NOT NULL DEFAULT 0,
  total_comments   INTEGER     NOT NULL DEFAULT 0,
  total_featured   INTEGER     NOT NULL DEFAULT 0,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_user_profiles_updated_at
  BEFORE UPDATE ON user_profiles
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 19. analytics_events
-- ---------------------------------------------------------------------------

CREATE TABLE analytics_events (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type    TEXT        NOT NULL,
  resource_type TEXT,
  resource_id   TEXT,
  metadata      JSONB,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 20. marketing_compliance
-- ---------------------------------------------------------------------------

CREATE TABLE marketing_compliance (
  id                 UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  moment_id          UUID        NOT NULL REFERENCES moments(id) ON DELETE CASCADE,
  broadcast_id       UUID        NOT NULL REFERENCES broadcasts(id) ON DELETE CASCADE,
  template_used      TEXT,
  template_category  TEXT,
  sponsor_disclosed  BOOLEAN     NOT NULL DEFAULT false,
  opt_out_included   BOOLEAN     NOT NULL DEFAULT false,
  pwa_link_included  BOOLEAN     NOT NULL DEFAULT false,
  compliance_score   INTEGER     NOT NULL CHECK (compliance_score BETWEEN 0 AND 100),
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 21. budget_transactions
-- ---------------------------------------------------------------------------

CREATE TABLE budget_transactions (
  id                 UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  campaign_id        UUID          NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  transaction_type   TEXT          NOT NULL CHECK (transaction_type IN ('spend','refund','adjustment')),
  amount             DECIMAL(10,2) NOT NULL,
  recipient_count    INTEGER       NOT NULL,
  cost_per_recipient DECIMAL(6,4)  NOT NULL DEFAULT 0.05,
  status             TEXT          NOT NULL CHECK (status IN ('completed','pending','failed')),
  created_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 22. system_settings
-- ---------------------------------------------------------------------------

CREATE TABLE system_settings (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  setting_key   TEXT        NOT NULL UNIQUE,
  setting_value TEXT        NOT NULL,
  description   TEXT,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_system_settings_updated_at
  BEFORE UPDATE ON system_settings
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 23. feature_flags
-- ---------------------------------------------------------------------------

CREATE TABLE feature_flags (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  flag_key    TEXT        NOT NULL UNIQUE,
  enabled     BOOLEAN     NOT NULL DEFAULT false,
  description TEXT,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_feature_flags_updated_at
  BEFORE UPDATE ON feature_flags
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 24. rate_limits
-- ---------------------------------------------------------------------------

CREATE TABLE rate_limits (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  identifier    TEXT        NOT NULL,
  endpoint      TEXT        NOT NULL,
  request_count INTEGER     NOT NULL DEFAULT 1,
  window_start  TIMESTAMPTZ NOT NULL,
  UNIQUE (identifier, endpoint)
);

-- ---------------------------------------------------------------------------
-- 25. audit_logs
-- ---------------------------------------------------------------------------

CREATE TABLE audit_logs (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       TEXT        NOT NULL,
  action        TEXT        NOT NULL,
  resource_type TEXT        NOT NULL,
  resource_id   TEXT        NOT NULL,
  changes       JSONB,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 26. error_logs
-- ---------------------------------------------------------------------------

CREATE TABLE error_logs (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  error_type    TEXT        NOT NULL,
  error_message TEXT        NOT NULL,
  context       JSONB,
  severity      TEXT        NOT NULL CHECK (severity IN ('low','medium','high','critical')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- DB Functions
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION lookup_authority(p_user_identifier TEXT)
RETURNS TABLE (
  id               UUID,
  user_identifier  TEXT,
  authority_level  INTEGER,
  role_label       TEXT,
  scope            TEXT,
  scope_identifier TEXT,
  approval_mode    TEXT,
  blast_radius     INTEGER,
  risk_threshold   DECIMAL,
  status           TEXT,
  valid_until      TIMESTAMPTZ,
  metadata         JSONB
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    ap.id, ap.user_identifier, ap.authority_level, ap.role_label,
    ap.scope, ap.scope_identifier, ap.approval_mode, ap.blast_radius,
    ap.risk_threshold, ap.status, ap.valid_until, ap.metadata
  FROM authority_profiles ap
  WHERE ap.user_identifier = p_user_identifier
    AND ap.status = 'active'
    AND (ap.valid_until IS NULL OR ap.valid_until > NOW())
  ORDER BY ap.authority_level DESC
  LIMIT 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION log_authority_action(
  p_authority_profile_id UUID,
  p_action               TEXT,
  p_actor_id             TEXT,
  p_context              JSONB DEFAULT NULL
) RETURNS VOID AS $$
BEGIN
  INSERT INTO authority_audit_log (authority_profile_id, action, actor_id, context)
  VALUES (p_authority_profile_id, p_action, p_actor_id, p_context);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

ALTER TABLE moments             ENABLE ROW LEVEL SECURITY;
ALTER TABLE sponsors            ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns           ENABLE ROW LEVEL SECURITY;
ALTER TABLE moment_intents      ENABLE ROW LEVEL SECURITY;
ALTER TABLE broadcasts          ENABLE ROW LEVEL SECURITY;
ALTER TABLE broadcast_batches   ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions       ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages            ENABLE ROW LEVEL SECURITY;
ALTER TABLE advisories          ENABLE ROW LEVEL SECURITY;
ALTER TABLE moderation_audit    ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments            ENABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_comments   ENABLE ROW LEVEL SECURITY;
ALTER TABLE authority_profiles  ENABLE ROW LEVEL SECURITY;
ALTER TABLE authority_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_roles         ENABLE ROW LEVEL SECURITY;
ALTER TABLE media               ENABLE ROW LEVEL SECURITY;
ALTER TABLE moment_stats        ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles       ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics_events    ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketing_compliance ENABLE ROW LEVEL SECURITY;
ALTER TABLE budget_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_settings     ENABLE ROW LEVEL SECURITY;
ALTER TABLE feature_flags       ENABLE ROW LEVEL SECURITY;
ALTER TABLE rate_limits         ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs          ENABLE ROW LEVEL SECURITY;
ALTER TABLE error_logs          ENABLE ROW LEVEL SECURITY;

-- moments
CREATE POLICY "moments_anon_read" ON moments
  FOR SELECT TO anon
  USING (status = 'broadcasted' AND publish_to_pwa = true);

CREATE POLICY "moments_auth_all" ON moments
  FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- sponsors
CREATE POLICY "sponsors_auth_read" ON sponsors
  FOR SELECT TO authenticated
  USING (true);

-- campaigns
CREATE POLICY "campaigns_auth_read" ON campaigns
  FOR SELECT TO authenticated
  USING (true);

-- moment_intents — service_role only (no anon/authenticated policies)

-- broadcasts
CREATE POLICY "broadcasts_auth_read" ON broadcasts
  FOR SELECT TO authenticated
  USING (true);

-- broadcast_batches — service_role only

-- subscriptions — service_role only

-- messages
CREATE POLICY "messages_auth_read" ON messages
  FOR SELECT TO authenticated
  USING (true);

-- advisories
CREATE POLICY "advisories_auth_read" ON advisories
  FOR SELECT TO authenticated
  USING (true);

-- moderation_audit
CREATE POLICY "moderation_audit_auth_read" ON moderation_audit
  FOR SELECT TO authenticated
  USING (true);

-- comments
CREATE POLICY "comments_anon_read" ON comments
  FOR SELECT TO anon
  USING (moderation_status = 'approved');

CREATE POLICY "comments_auth_all" ON comments
  FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

-- whatsapp_comments — service_role only

-- authority_profiles
CREATE POLICY "authority_profiles_auth_read" ON authority_profiles
  FOR SELECT TO authenticated
  USING (true);

-- authority_audit_log
CREATE POLICY "authority_audit_log_auth_read" ON authority_audit_log
  FOR SELECT TO authenticated
  USING (true);

-- admin_roles
CREATE POLICY "admin_roles_auth_read_own" ON admin_roles
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());

-- media — service_role only

-- moment_stats
CREATE POLICY "moment_stats_anon_read" ON moment_stats
  FOR SELECT TO anon
  USING (true);

-- user_profiles
CREATE POLICY "user_profiles_auth_read" ON user_profiles
  FOR SELECT TO authenticated
  USING (true);

-- analytics_events — service_role only

-- marketing_compliance
CREATE POLICY "marketing_compliance_auth_read" ON marketing_compliance
  FOR SELECT TO authenticated
  USING (true);

-- budget_transactions
CREATE POLICY "budget_transactions_auth_read" ON budget_transactions
  FOR SELECT TO authenticated
  USING (true);

-- system_settings
CREATE POLICY "system_settings_auth_read" ON system_settings
  FOR SELECT TO authenticated
  USING (true);

-- feature_flags
CREATE POLICY "feature_flags_auth_read" ON feature_flags
  FOR SELECT TO authenticated
  USING (true);

-- rate_limits — service_role only

-- audit_logs
CREATE POLICY "audit_logs_auth_read_own" ON audit_logs
  FOR SELECT TO authenticated
  USING (user_id = auth.uid()::text);

-- error_logs
CREATE POLICY "error_logs_auth_read" ON error_logs
  FOR SELECT TO authenticated
  USING (true);

-- ---------------------------------------------------------------------------
-- Seed: system_settings defaults
-- ---------------------------------------------------------------------------

INSERT INTO system_settings (setting_key, setting_value, description) VALUES
  ('monthly_budget',            '5000',  'Monthly broadcast budget in ZAR'),
  ('message_cost_zar',          '0.05',  'Cost per WhatsApp message in ZAR'),
  ('daily_message_limit',       '500',   'Maximum messages per day'),
  ('warning_threshold_percent', '80',    'Budget warning threshold as percentage')
ON CONFLICT (setting_key) DO NOTHING;
